#!/usr/bin/env python3

## example_function_name
## ExampleVariableName

import random


ListOfSettings =[
    'high fantasy', 'low fantasy', 'grim fantasy', 'age of sail', 'medieaval'
    'space opera', 'cyberpunk', 'urban fantasy', 'slice-of-life','post-apocalypse',
    'ancient legends', 'hard sci fi', 'steampunk', '1920s pulp', 'solarpunk',
    'pike and musket', 'victorina', 'colonial', 'diesel punk', 'dystopia', 
    'alternate history', 'biopunk', 'cold war', 'weird world war', 'superhero comic'
    ]

ListOfParties =[
    'circus', 'first responders', 'mercenaries', 'city gaurds', 'criminal gang',
    'merchant convoy', 'monster hunters', 'smugglers', 'traders',
    'investigators', 'boarding school', 'university dept', 'neighbours', 'village',
    'operatives', 'rebels', 'police','refugees','outsiders','beaureucrats'
    ]
    

ListOfThemes =[
'balance',
'belief',
'change',
'comfort',
'destruction ',
'corruption',
'family ',
'freedom',
'friendship',
'glory',
'honour',
'hunger',
'justice',
'knowledge ',
'law/tradition',
'love',
'pain',
'revenge',
'unity',
'survival',
'violence',
'wealth',
]

ListOfDeafaultMoves={
    'Stop Adding Moves',
    'Keep calm',
    'Ignore difficulties',
    'Take damage',
    'Act forcefully',
    'Act carefullly',
    'Act stylishly',
    'Seduce',
    'Persuade',
    'Threaten',
    'Assess',
    'Investigate',
    'Recall knowledge'
        }


def get_setting():
  Setting = random.randint(0, len(ListOfSettings)-1)
  Party = random.randint(0, len(ListOfParties)-1)
  Setting = ListOfSettings[Setting]
  Party = ListOfParties[Party]
  FullSetting = Party+' in '+Setting
  return(FullSetting)

def get_premise():
  ThemeA = random.randint(0, len(ListOfThemes)-1)
  ThemeB = random.randint(0, len(ListOfThemes)-1)
  ThemeA = ListOfThemes[ThemeA]
  ThemeB = ListOfThemes[ThemeB]
  return(ThemeA, ThemeB)

def get_seed():
    Title = input('What is your game called?')
    Setting = input('What is the broad setting? High Fantasy? Cyberpunk? ')
    if Setting == '':
        Setting = get_setting()
    if Title == '':
        i=int(len(Setting)/3)
        Title = Setting[:i]+Setting[i*2:] + ' World'
        Title = Title.upper() 
    return(Title, Setting)
        
def rank_prems(PremA, PremB):
    PremARank = input('How important to the game expereience is ', PremA, 
                      " : 0= random 1 = Very, has a dedicated mechanic, 2= A bit, has a dedicated stat, 3= not, ignore it.")
    PremBRank =  input('How important is ', PremB, 
                       " : 0= random, 1 = Very, has a dedicated mechanic, 2= A bit, has a dedicated stat, 3= not, ignore it.")
    if PremARank == '' or PremARank == '0':
        PremARank = random.randint(1,3)
    if PremBRank == '' or PremBRank == '0':
        PremBRank = random.randint(1,3)
    if PremARank == '3' and PremBRank == '3':
        print('your games needs to be about something')
        PremA, PremB = getpremise()
        PremARank, PremBrank = rank_prems(PremA, PremB)
      
      

## Main

## TODO
## Do you know what the heart of yourgame is?
## yes
## no -> PremA, PremB = get_premise()

## How important is PremA - Very, A bit, not
## if both not PremA, PremB = get_premise()
## very = lookup_mechanic
## a bit = statA, StatB

Title, Setting = get_seed()
PremA, PremB = get_premise() ## replace this
print(Title)
print('A', Setting, ' about ', PremA,' and ', PremB)



print('Choose some of these deafult moves (five is common, zero is possible, all twelve waters down the playbooks a bit.')
for index, move in enumerate(ListOfDeafaultMoves):
    print(index, ' : ', move)
#print(ListOfStats)
KeyIndex =5 ## inital value only
while KeyIndex !=0:
    KeyIndex= int(input('Number of move on list above  '))
    StatName= input('Name of the Stat you roll for that  ')
    MoveName= input('Custom Move name, (or leave blank for deafult  ')
                                        
      



